import { FetishData } from './types';

// AJUSTE AQUI: Substitua os links abaixo pelos seus links reais da Ticto
const BASE_TICTO_URL = "https://checkout.ticto.com.br"; 

export const FETISH_DATA: FetishData[] = [
  {
    id: 'anal',
    rank: 1,
    title: 'Sexo Anal',
    iconName: 'CircleDot',
    color: 'from-brand-900/50 to-dark-900',
    popularity: 70,
    stats: {
      men: 'Top absoluto nacional (~70%). Líder no Norte/Nordeste.',
      women: 'Alto como receptivo ou ativo (pegging em crescimento).',
      lgbt: 'Muito comum em cenas gay e lésbica.',
    },
    products: {
      Homens: {
        introTitle: 'Introdução ao Anal Masculino',
        introDesc: 'Guia do Zero ao Prazer Prostático Seguro.',
        bumpTitle: 'Nível Avançado: Passivo & Próstata',
        bumpDesc: 'Posições passivas, guia de plugs avançados e técnicas de milking.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: `${BASE_TICTO_URL}/ANAL_M_BUNDLE`,
      },
      Mulheres: {
        introTitle: 'Anal Feminino: Comunicação & Prazer',
        introDesc: 'Técnicas de relaxamento e lubrificação.',
        bumpTitle: 'Avançado: Pegging & Dupla Penetração',
        bumpDesc: 'Tutorial de strap-on, posições ativas e segurança na DP.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: `${BASE_TICTO_URL}/ANAL_F_BUNDLE`,
      },
      'LGBT+': {
        introTitle: 'Anal Queer: Fluidez e Prazer',
        introDesc: 'Guia inclusivo para papéis versáteis.',
        bumpTitle: 'Variações Queer & Fisting',
        bumpDesc: 'Brinquedos avançados, fisting consensual e dinâmicas intensas.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: `${BASE_TICTO_URL}/ANAL_LGBT_BUNDLE`,
      },
    },
  },
  {
    id: 'podolatria',
    rank: 2,
    title: 'Podolatria',
    iconName: 'Footprints',
    color: 'from-brand-900/30 to-dark-900',
    popularity: 65,
    stats: {
      men: 'Líder em conteúdos personalizados (FanFever).',
      women: 'Crescente, adoração passiva ou ativa.',
      lgbt: 'Popular em comunidades kink queer.',
    },
    products: {
      Homens: {
        introTitle: 'Manual da Adoração aos Pés',
        introDesc: 'Como idolatrar de forma respeitosa e intensa.',
        bumpTitle: 'Trampling & Submissão',
        bumpDesc: 'Roleplay de capacho humano e ser pisado com segurança.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
      Mulheres: {
        introTitle: 'Poder nos Pés',
        introDesc: 'Como receber adoração e dominar.',
        bumpTitle: 'Dominação Podólatra',
        bumpDesc: 'Técnicas de pisar, humilhação leve e controle financeiro.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
      'LGBT+': {
        introTitle: 'Exploração Sensorial Queer',
        introDesc: 'Toque e adoração sem gênero definido.',
        bumpTitle: 'Pés no BDSM Queer',
        bumpDesc: 'Integração com bondage e jogos de poder.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
    },
  },
  {
    id: 'orgia',
    rank: 3,
    title: 'Orgia / Grupo',
    iconName: 'Users',
    color: 'from-dark-800 to-dark-900',
    popularity: 55,
    stats: {
      men: 'Top 3 nacional (Sudeste/Sul).',
      women: 'Fantasia alta (~45% em pesquisas).',
      lgbt: 'Comum em festas liberais queer.',
    },
    products: {
      Homens: {
        introTitle: 'Manual do Sexo em Grupo',
        introDesc: 'Etiqueta, festas e consentimento coletivo.',
        bumpTitle: 'Gang Bang Passivo/Ativo',
        bumpDesc: 'Dinâmicas de múltiplos parceiros e gerenciamento de energia.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
      Mulheres: {
        introTitle: 'A Mulher no Centro',
        introDesc: 'Segurança, seleção de parceiros e prazer.',
        bumpTitle: 'Orgia Avançada',
        bumpDesc: 'Múltiplos orgasmos e etiqueta para festas liberais.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
      'LGBT+': {
        introTitle: 'Festas Queer & Darkrooms',
        introDesc: 'Navegando espaços seguros e códigos.',
        bumpTitle: 'Poliamor e Orgias',
        bumpDesc: 'Acordos emocionais para grupos fixos ou casuais.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
    },
  },
  {
    id: 'cuckold',
    rank: 4,
    title: 'Cuckold',
    iconName: 'Eye',
    color: 'from-dark-800 to-dark-900',
    popularity: 48,
    stats: {
      men: 'Muito alto no Norte/Nordeste.',
      women: 'Hotwife ou observadora.',
      lgbt: 'Variações em casais bi/poliamor.',
    },
    products: {
      Homens: {
        introTitle: 'Introdução ao Cuckold',
        introDesc: 'O prazer de assistir e a psicologia da fantasia.',
        bumpTitle: 'Encontros Reais & Apps',
        bumpDesc: 'Como encontrar o terceiro (Bull) e scripts de negociação.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
      Mulheres: {
        introTitle: 'Guia Hotwife Empoderada',
        introDesc: 'Como escolher parceiros e definir limites.',
        bumpTitle: 'Lifestyle Avançado',
        bumpDesc: 'Viagens, múltiplos Bulls e gestão emocional do parceiro.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
      'LGBT+': {
        introTitle: 'Cuckold Fluido',
        introDesc: 'Dinâmicas para casais bi e trans.',
        bumpTitle: 'Voyeurismo Queer',
        bumpDesc: 'Assistir o parceiro em cenas gays/lésbicas com segurança.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
    },
  },
  {
    id: 'bdsm',
    rank: 5,
    title: 'Dominação / Sub',
    iconName: 'Gavel', // Alternativa: Lock
    color: 'from-dark-800 to-dark-900',
    popularity: 45,
    stats: {
      men: 'Submissão alta (humilhação).',
      women: 'Dominação e submissão ativa.',
      lgbt: 'Líder em cenas (bondage, pet play).',
    },
    products: {
      Homens: {
        introTitle: 'Manual do Submisso Consciente',
        introDesc: 'Servir com segurança e profundidade.',
        bumpTitle: 'Bondage & Impacto',
        bumpDesc: 'Nós básicos, shibari inicial e ferramentas de impacto.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
      Mulheres: {
        introTitle: 'Desperte a Dominatrix',
        introDesc: 'Voz de comando, postura e psicologia do poder.',
        bumpTitle: 'Ferramentas de Dor',
        bumpDesc: 'Chicotes, palmatórias e segurança física.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
      'LGBT+': {
        introTitle: 'Kink Queer: Papéis Fluidos',
        introDesc: 'Switch, negociação e bondage inclusivo.',
        bumpTitle: 'Pet Play & Primal',
        bumpDesc: 'Roleplay animal, hoods e dinâmicas instintivas.',
        bumpPrice: 67,
        checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`,
        bundleUrl: '#',
      },
    },
  },
  {
    id: 'voyeur',
    rank: 6,
    title: 'Voyeurismo',
    iconName: 'KeyRound',
    color: 'from-dark-800 to-dark-900',
    popularity: 42,
    stats: {
      men: 'Alto (Centro-Oeste/DF).',
      women: 'Combinado com exibicionismo.',
      lgbt: 'Popular em apps e festas.',
    },
    products: {
      Homens: { introTitle: 'A Arte de Observar', introDesc: 'Ética, prazer visual e ambientes certos.', bumpTitle: 'Clubes de Swing', bumpDesc: 'Guia de etiqueta para solteiros em clubes.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      Mulheres: { introTitle: 'Ser Observada', introDesc: 'O poder e o prazer do olhar alheio.', bumpTitle: 'Voyeurismo Mútuo', bumpDesc: 'Jogos de observação para casais.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      'LGBT+': { introTitle: 'Cruising & Prazer Visual', introDesc: 'Segurança e ética em encontros visuais.', bumpTitle: 'Cenas Públicas', bumpDesc: 'Guia de festas e darkrooms.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
    },
  },
  {
    id: 'menage',
    rank: 7,
    title: 'Ménage à Trois',
    iconName: 'Triangle',
    color: 'from-dark-800 to-dark-900',
    popularity: 40,
    stats: {
      men: 'Fantasia top (~45%).',
      women: 'Alta (87-95% já fantasiaram).',
      lgbt: 'Muito comum em bi e polissexual.',
    },
    products: {
      Homens: { introTitle: 'Guia do Trio (MMF)', introDesc: 'Como incluir outro sem ciúmes ou tensão.', bumpTitle: 'Posições Grupais', bumpDesc: 'Coreografia para 3 corpos.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      Mulheres: { introTitle: 'Guia do Trio (FFM)', introDesc: 'Explorando com outra mulher com segurança.', bumpTitle: 'Sensorial a Três', bumpDesc: 'Foco no toque e massagem mútua.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      'LGBT+': { introTitle: 'Trios Queer', introDesc: 'Dinâmicas além do binário.', bumpTitle: 'Poliamor Inicial', bumpDesc: 'Diferença entre ménage e trisal.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
    },
  },
  {
    id: 'asmr',
    rank: 8,
    title: 'ASMR Erótico',
    iconName: 'Headphones',
    color: 'from-dark-800 to-dark-900',
    popularity: 35,
    stats: {
      men: 'Crescente em conteúdos personalizados.',
      women: 'Sensorial e relaxante, alta demanda.',
      lgbt: 'Adaptado em roleplays queer.',
    },
    products: {
      Homens: { introTitle: 'Áudio & Imersão', introDesc: 'O poder dos sussurros e sons controlados.', bumpTitle: 'Scripts Submissos', bumpDesc: 'Áudios prontos de comando.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      Mulheres: { introTitle: 'Controle Auditivo', introDesc: 'Como usar a voz para excitar e dominar.', bumpTitle: 'Gravação Caseira', bumpDesc: 'Crie seus próprios áudios para ele.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      'LGBT+': { introTitle: 'Sons Queer', introDesc: 'Narrativas inclusivas e ASMR BDSM.', bumpTitle: 'ASMR BDSM', bumpDesc: 'Sons de impacto e restrição.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
    },
  },
  {
    id: 'exibicionismo',
    rank: 9,
    title: 'Exibicionismo',
    iconName: 'Aperture', // Camera lens look
    color: 'from-brand-900/20 to-dark-900',
    popularity: 30,
    stats: {
      men: 'Comum em swing e público.',
      women: 'Crescente (sexo em público).',
      lgbt: 'Alto em festas temáticas.',
    },
    products: {
      Homens: { introTitle: 'Nudez Pública Calculada', introDesc: 'A adrenalina do risco com segurança.', bumpTitle: 'Dogging Seguro', bumpDesc: 'Locais e códigos de farol.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      Mulheres: { introTitle: 'Exibicionismo Digital', introDesc: 'Fotos, vídeos anônimos e controle da imagem.', bumpTitle: 'Flash em Público', bumpDesc: 'Roupas discretas e locais rápidos.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      'LGBT+': { introTitle: 'Performance Queer', introDesc: 'Montação e destaque em espaços seguros.', bumpTitle: 'Festas Temáticas', bumpDesc: 'Onde se exibir com segurança.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
    },
  },
  {
    id: 'pegging',
    rank: 10,
    title: 'Pegging',
    iconName: 'ArrowDownUp',
    color: 'from-brand-900/30 to-dark-900',
    popularity: 28,
    stats: {
      men: 'Crescimento explosivo (>200%).',
      women: 'Dominação ativa alta.',
      lgbt: 'Clássico em cenas gay e lésbica.',
    },
    products: {
      Homens: { introTitle: 'Aceitando a Inversão', introDesc: 'Superando barreiras e maximizando o prazer.', bumpTitle: 'Posições Submissas', bumpDesc: 'Como receber com prazer máximo.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      Mulheres: { introTitle: 'Guia do Strap-on', introDesc: 'Equipamento, técnica e controle total.', bumpTitle: 'Técnicas de Estocada', bumpDesc: 'Ritmo, profundidade e controle.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      'LGBT+': { introTitle: 'Versatilidade Total', introDesc: 'Fluindo entre papéis com segurança.', bumpTitle: 'Brinquedos Duplos', bumpDesc: 'Double-ended e prazer simultâneo.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
    },
  },
  {
    id: 'roleplay',
    rank: 11,
    title: 'Roleplay',
    iconName: 'Drama', // Masks
    color: 'from-dark-800 to-dark-900',
    popularity: 25,
    stats: {
      men: 'Policial, professor etc.',
      women: 'Alta em BDSM e poder.',
      lgbt: 'Muito variado (primal, breeding).',
    },
    products: {
      Homens: { introTitle: 'Personagens & Poder', introDesc: 'Como entrar em cena e manter a imersão.', bumpTitle: 'Roteiros Prontos', bumpDesc: 'Scripts para médico, ladrão, etc.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      Mulheres: { introTitle: 'Autoridade & Sedução', introDesc: 'Roleplay de chefe, policial e dominatrix.', bumpTitle: 'Figurinos', bumpDesc: 'Onde comprar e como improvisar.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      'LGBT+': { introTitle: 'Puppy Play & Pet Kink', introDesc: 'Intro ao universo pet e primal play.', bumpTitle: 'Breeding Kink', bumpDesc: 'Fantasias de reprodução adaptadas.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
    },
  },
  {
    id: 'humilhacao',
    rank: 12,
    title: 'Humilhação',
    iconName: 'MessageSquareWarning',
    color: 'from-dark-800 to-dark-900',
    popularity: 20,
    stats: {
      men: 'Submissão verbal alta (SPH).',
      women: 'Dominação verbal crescente.',
      lgbt: 'Comum em kink queer.',
    },
    products: {
      Homens: { introTitle: 'Prazer na Submissão Verbal', introDesc: 'Psicologia da humilhação e seus limites.', bumpTitle: 'SPH (Small Penis)', bumpDesc: 'Humilhação de tamanho e impotência.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      Mulheres: { introTitle: 'Dominação Verbal Refinada', introDesc: 'Como humilhar com controle e intenção.', bumpTitle: 'Lista de Insultos', bumpDesc: '50 frases prontas para usar.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
      'LGBT+': { introTitle: 'Degradação Consensual', introDesc: 'Limites, aftercare e controle psicológico.', bumpTitle: 'Escravidão Mental', bumpDesc: 'Jogos de controle psicológico.', bumpPrice: 67, checkoutUrl: `${BASE_TICTO_URL}/O152D8A61`, bundleUrl: '#' },
    },
  },
];
